services:
  - type: web
    name: iris
    runtime: node
    buildCommand: yarn install && yarn nx build iris --prod
    startCommand: yarn nx run iris:serve:production --port=$PORT --hostname=0.0.0.0
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4200
